# Docker Setup
services:
  node:
    hostname: node.local.dev
    image: 'node:20.13.1'
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    command: tail -f /dev/null
    ports:
      - '3000:3000'
      - '8001:8001'
      - '4173:4173'
      - '5173:5173'
    expose:
      - "8081"
      - '3000'
      - '4173'
      - '5173'
    volumes:
      - '.:/home/node/app:delegated'
    networks:
      node-network:
        aliases:
          - node.local.dev
networks:
  node-network:
    driver: bridge
